### ISSUE TITLE
attachToDocument configuration flag

### ISSUE THREAD

**Issue by mpi** [Pragmatists/angular-test-runner#8]
Some components and libraries require to be attached to the `document` in order to work correctly (for example if they interact with scrollbars). 

Provide flag that will force angular-test-runner to attach tested application to document before each test.
**Important:** after each test application has to be detached from document.

Suggestion:
```javascript
var app = test.app([/*...*/], { attachToDocument: true });
```

**Comment by zbychupragmatists** [comment]
Implemented in 0.0.6
